package org.labormanagement.service

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.BeforeEach
import org.labormanagement.database.DatabaseFactory
import org.labormanagement.model.*
import org.labormanagement.repository.BusinessRepository
import org.labormanagement.repository.EmployeeRepository
import org.labormanagement.optimization.OptimizationConverter
import org.labormanagement.repository.SalesForecastRepository
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.LocalTime
import java.util.UUID

/**
 * Scheduling a business whose day runs past midnight.
 *
 * The solver's slots were generated by walking a LocalTime forward while it stayed below
 * the closing time. A business open 21:00-02:00 closes at a LocalTime *smaller* than the
 * one it opened at, so that loop ended before it began and produced no slots at all: the
 * solver had nothing to assign, returned an empty schedule, and fell back to greedy - with
 * no error anywhere to say why the grid came back blank.
 */
class OvernightHoursTest {

    private val testBusinessId = UUID.fromString("00000000-0000-0000-0000-000000000006")
    private lateinit var employeeRepository: EmployeeRepository
    private lateinit var businessRepository: BusinessRepository

    companion object {
        @JvmStatic
        @BeforeAll
        fun initDatabase() {
            DatabaseFactory.init(
                jdbcUrl = System.getenv("TEST_DATABASE_URL")
                    ?: "jdbc:postgresql://localhost:5432/labormanagement_test",
                user = System.getenv("TEST_DATABASE_USER") ?: "shirleyhe",
                password = System.getenv("TEST_DATABASE_PASSWORD") ?: ""
            )
        }
    }

    private val monday = LocalDate.of(2026, 9, 7)

    @BeforeEach
    fun setup() {
        DatabaseFactory.resetDatabase()
        businessRepository = BusinessRepository()
        employeeRepository = EmployeeRepository()
    }

    private fun createBusiness(open: LocalTime, close: LocalTime) {
        businessRepository.create(
            Business(
                id = testBusinessId,
                name = "Late Night Venue",
                ownerId = "test-owner",
                settings = BusinessSettings(defaultOpenTime = open, defaultCloseTime = close)
            )
        )
    }

    /** Someone available across the whole overnight window, on every day. */
    private fun nightEmployee(name: String, from: String = "20:00", to: String = "03:00"): Employee {
        val e = Employee(
            businessId = testBusinessId,
            firstName = name,
            lastName = "Test",
            dateOfBirth = LocalDate.of(1990, 1, 1),
            normalPayRate = 15.0,
            overtimePayRate = 22.5,
            productivity = 100.0,
            contract = Contract(
                contractedHoursPerWeek = 40.0,
                maxHoursPerWeek = 60.0,
                maxHoursPerDay = 12.0,
                overtimeThreshold = 40.0
            ),
            availability = DayOfWeek.entries.map {
                Availability(
                    availabilityType = AvailabilityType.WEEKLY_RECURRING,
                    dayOfWeek = it,
                    startTime = LocalTime.parse(from),
                    endTime = LocalTime.parse(to)
                )
            }
        )
        employeeRepository.create(e)
        return e
    }

    /**
     * Demand across the late-night window, on both sides of midnight.
     *
     * Without this the solver has no reason to staff anyone and returns an empty schedule
     * that looks exactly like a broken constraint - which is how the missing 23:00 hour
     * stayed hidden from tests that asserted only "some shifts exist".
     */
    private fun seedLateNightForecast() {
        val hours = listOf(20, 21, 22, 23, 0, 1, 2).associate { LocalTime.of(it, 0) to 400.0 }
        SalesForecastRepository().updateForBusiness(
            businessId = testBusinessId,
            weeklyPattern = DayOfWeek.entries.associateWith { hours },
            updatedBy = "test"
        )
    }

    private fun generate(
        startDate: LocalDate,
        endDate: LocalDate,
        employees: List<Employee>,
        approach: SchedulingApproach = SchedulingApproach.OPTIMIZER
    ): Schedule {
        val scheduler = ShiftScheduler(schedulingApproach = approach)
        return scheduler.generateSchedule(
            input = ScheduleInput(
                businessId = testBusinessId,
                employeeIds = employees.map { it.id },
                laborCostBudget = Double.MAX_VALUE,
                schedulePeriod = SchedulePeriod(
                    startDate = startDate,
                    endDate = endDate,
                    operatingHours = emptyMap()
                ),
                optimizationObjective = OptimizationObjective.MAXIMIZE_SALES
            ),
            name = "Overnight test",
            generatedBy = "test",
            businessId = testBusinessId
        )
    }

    @Test
    fun `a business open past midnight is scheduled at all`() {
        createBusiness(LocalTime.of(21, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice")
        seedLateNightForecast()

        val schedule = generate(monday, monday, listOf(alice))

        assertTrue(
            schedule.shifts.isNotEmpty(),
            "an overnight business produced no shifts - the slot loop never ran"
        )
    }

    @Test
    fun `overnight shifts carry their true duration`() {
        createBusiness(LocalTime.of(21, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice")
        seedLateNightForecast()

        val schedule = generate(monday, monday, listOf(alice))
        val total = schedule.shifts.sumOf { it.durationHours }

        // The window is 5 hours long; nobody can be credited with more than that.
        assertTrue(total > 0.0, "no hours scheduled")
        assertTrue(total <= 5.0, "credited $total hours for a 5 hour window")
    }

    @Test
    fun `a shift running past midnight stays one shift`() {
        // Split at the boundary it would read as two short shifts rather than one
        // continuous block, which is not what anyone worked.
        createBusiness(LocalTime.of(22, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice", from = "21:00", to = "03:00")
        seedLateNightForecast()

        val schedule = generate(monday, monday, listOf(alice))
        val aliceShifts = schedule.shifts.filter { it.employeeId == alice.id }

        assertTrue(aliceShifts.isNotEmpty(), "no shifts generated")
        // One block, possibly split by the overtime threshold but not by midnight.
        val crossesMidnight = aliceShifts.any { it.endTime <= it.startTime }
        val startsAtMidnight = aliceShifts.any { it.startTime == LocalTime.MIDNIGHT }
        assertTrue(
            crossesMidnight || !startsAtMidnight,
            "the block was cut at midnight: ${aliceShifts.map { "${it.startTime}-${it.endTime}" }}"
        )
    }

    @Test
    fun `hours after midnight land on the day they are worked`() {
        // Calendar-day attribution: the small hours count against the date they fall on.
        createBusiness(LocalTime.of(21, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice")
        seedLateNightForecast()

        val schedule = generate(monday, monday, listOf(alice))

        // The block starts on Monday, so its shift row is dated Monday and its duration
        // covers the post-midnight tail.
        assertTrue(schedule.shifts.all { it.date == monday })
        assertTrue(schedule.shifts.any { it.endTime <= it.startTime || it.endTime <= LocalTime.of(2, 0) })
    }

    @Test
    fun `one overnight shift is not counted as two days worked`() {
        // Consecutive-days and weekly-rest reason in whole days off. If the tail of a
        // Monday night marked Tuesday as worked, a run of night shifts would trip the
        // consecutive-days limit off a schedule nobody would call excessive.
        createBusiness(LocalTime.of(21, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice")
        seedLateNightForecast()

        val schedule = generate(monday, monday.plusDays(6), listOf(alice))

        assertTrue(schedule.shifts.isNotEmpty(), "no shifts generated across the week")
        // Every shift row is dated to the night it belongs to, never to the morning after.
        val dates = schedule.shifts.map { it.date }.toSet()
        assertTrue(
            dates.all { it in monday..monday.plusDays(6) },
            "a shift was dated outside the schedule period: $dates"
        )
    }

    @Test
    fun `the hour before a midnight close still draws its forecast`() {
        // The 23:00-00:00 slot ends at a LocalTime of 00:00, and "before 00:00" is false
        // for every hour there is, so this slot matched no forecast entry and was handed
        // to the solver as zero demand. Asserted on the projected sales rather than on the
        // resulting shifts: under MAXIMIZE_SALES with spare labour the hour gets staffed
        // either way, which is exactly why the gap survived an end-to-end eyeball and only
        // showed up as an unstaffed hour once demand was the binding factor.
        createBusiness(LocalTime.of(21, 0), LocalTime.of(2, 0))
        val alice = nightEmployee("Alice")
        seedLateNightForecast()

        val input = OptimizationConverter.buildOptimizationInput(
            employees = listOf(alice),
            salesForecast = SalesForecastRepository().getByBusiness(testBusinessId),
            scheduleDates = listOf(monday),
            operatingHoursMap = mapOf(monday to Pair(LocalTime.of(21, 0), LocalTime.of(2, 0))),
            businessId = testBusinessId
        )

        val lastHourBeforeMidnight = input.timeSlots.indexOfFirst { it.startTime == LocalTime.of(23, 0) }
        assertTrue(lastHourBeforeMidnight >= 0, "no 23:00 slot was generated at all")
        assertEquals(
            400.0,
            input.projectedSales[lastHourBeforeMidnight],
            0.001,
            "the 23:00-00:00 slot drew no demand, so nothing would staff it"
        )
    }

    @Test
    fun `an ordinary daytime business is unaffected`() {
        // The wrap handling must not disturb the normal case.
        createBusiness(LocalTime.of(9, 0), LocalTime.of(17, 0))
        val alice = nightEmployee("Alice", from = "08:00", to = "18:00")

        val schedule = generate(monday, monday, listOf(alice))

        assertTrue(schedule.shifts.isNotEmpty())
        assertTrue(
            schedule.shifts.all { it.startTime >= LocalTime.of(9, 0) && it.endTime <= LocalTime.of(17, 0) },
            "daytime hours drifted: ${schedule.shifts.map { "${it.startTime}-${it.endTime}" }}"
        )
    }

    @Test
    fun `an employee unavailable after midnight is not given the small hours`() {
        // Availability still has to bound the window - the wrap fix must not make
        // everyone available for everything.
        createBusiness(LocalTime.of(20, 0), LocalTime.of(3, 0))
        val earlyFinisher = nightEmployee("Early", from = "20:00", to = "23:00")
        seedLateNightForecast()

        val schedule = generate(monday, monday, listOf(earlyFinisher))

        schedule.shifts.forEach { shift ->
            assertTrue(
                shift.startTime >= LocalTime.of(20, 0) && shift.endTime <= LocalTime.of(23, 0),
                "assigned outside their availability: ${shift.startTime}-${shift.endTime}"
            )
        }
    }
}
