package org.labormanagement.repository

import org.labormanagement.model.ScheduleHistory
import java.time.Instant
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * Repository for managing schedule generation audit history.
 * Stores complete snapshots of schedule generations for historical analysis and compliance.
 * For now, uses in-memory storage. In production, this would persist to a database.
 */
class ScheduleHistoryRepository {
    private val history = ConcurrentHashMap<UUID, ScheduleHistory>()

    /**
     * Save a schedule history record
     */
    fun save(scheduleHistory: ScheduleHistory): ScheduleHistory {
        history[scheduleHistory.id] = scheduleHistory
        return scheduleHistory
    }

    /**
     * Get a specific schedule history record by ID
     */
    fun findById(id: UUID): ScheduleHistory? {
        return history[id]
    }

    /**
     * Get all schedule history records, sorted by generation time (newest first)
     */
    fun findAll(): List<ScheduleHistory> {
        return history.values
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get schedule history records with pagination
     */
    fun findAll(limit: Int = 50, offset: Int = 0): List<ScheduleHistory> {
        return history.values
            .sortedByDescending { it.generatedAt }
            .drop(offset)
            .take(limit)
            .toList()
    }

    /**
     * Get schedule history records generated after a specific timestamp
     */
    fun findAfter(timestamp: Instant): List<ScheduleHistory> {
        return history.values
            .filter { it.generatedAt.isAfter(timestamp) }
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get schedule history records generated by a specific user
     */
    fun findByGeneratedBy(generatedBy: String): List<ScheduleHistory> {
        return history.values
            .filter { it.generatedBy == generatedBy }
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get the most recent schedule history record
     */
    fun findLatest(): ScheduleHistory? {
        return history.values
            .maxByOrNull { it.generatedAt }
    }

    /**
     * Delete a schedule history record
     */
    fun delete(id: UUID): Boolean {
        return history.remove(id) != null
    }

    /**
     * Delete all schedule history records older than a specific timestamp
     */
    fun deleteOlderThan(timestamp: Instant): Int {
        val toDelete = history.values
            .filter { it.generatedAt.isBefore(timestamp) }
            .map { it.id }

        toDelete.forEach { history.remove(it) }
        return toDelete.size
    }

    /**
     * Get total count of history records
     */
    fun count(): Int {
        return history.size
    }

    /**
     * Clear all history records (for testing)
     */
    fun clear() {
        history.clear()
    }
}