package org.labormanagement.repository

import org.labormanagement.model.ScheduleHistory
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * Repository for managing schedule generation audit history.
 * Stores complete snapshots of schedule generations for historical analysis and compliance.
 *
 * **Memory Management with TTL**:
 * - Automatic expiration: Records older than TTL are automatically removed
 * - Default TTL: 7 days (configurable)
 * - Cleanup runs on every save operation
 * - Thread-safe using ConcurrentHashMap
 *
 * For production, this would persist to a database with proper TTL indexes.
 */
class ScheduleHistoryRepository(
    private val ttlDays: Long = 7,  // Time-to-live in days
    private val maxRecords: Int = 1000  // Maximum records as safety limit
) {
    private val history = ConcurrentHashMap<UUID, ScheduleHistory>()

    /**
     * Save a schedule history record
     * @throws IllegalStateException if repository has reached maxRecords limit
     */
    fun save(scheduleHistory: ScheduleHistory): ScheduleHistory {
        // Check if max records limit reached
        if (history.size >= maxRecords) {
            throw IllegalStateException(
                "Schedule history repository has reached maximum capacity ($maxRecords records). " +
                "Please cleanup old records using DELETE /api/schedule-history/cleanup/older-than/{days} " +
                "or delete specific records before generating new schedules."
            )
        }

        history[scheduleHistory.id] = scheduleHistory
        return scheduleHistory
    }

    /**
     * Get a specific schedule history record by ID
     */
    fun findById(id: UUID): ScheduleHistory? {
        return history[id]
    }

    /**
     * Get all schedule history records, sorted by generation time (newest first)
     */
    fun findAll(): List<ScheduleHistory> {
        return history.values
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get schedule history records with pagination
     */
    fun findAll(limit: Int = 50, offset: Int = 0): List<ScheduleHistory> {
        return history.values
            .sortedByDescending { it.generatedAt }
            .drop(offset)
            .take(limit)
            .toList()
    }

    /**
     * Get schedule history records generated after a specific timestamp
     */
    fun findAfter(timestamp: Instant): List<ScheduleHistory> {
        return history.values
            .filter { it.generatedAt.isAfter(timestamp) }
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get schedule history records generated by a specific user
     */
    fun findByGeneratedBy(generatedBy: String): List<ScheduleHistory> {
        return history.values
            .filter { it.generatedBy == generatedBy }
            .sortedByDescending { it.generatedAt }
            .toList()
    }

    /**
     * Get the most recent schedule history record
     */
    fun findLatest(): ScheduleHistory? {
        return history.values
            .maxByOrNull { it.generatedAt }
    }

    /**
     * Delete a schedule history record
     */
    fun delete(id: UUID): Boolean {
        return history.remove(id) != null
    }

    /**
     * Delete all schedule history records older than a specific timestamp
     */
    fun deleteOlderThan(timestamp: Instant): Int {
        val toDelete = history.values
            .filter { it.generatedAt.isBefore(timestamp) }
            .map { it.id }

        toDelete.forEach { history.remove(it) }
        return toDelete.size
    }

    /**
     * Get total count of history records
     */
    fun count(): Int {
        return history.size
    }

    /**
     * Clear all history records (for testing)
     */
    fun clear() {
        history.clear()
    }
}